name = "dodo"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# For pay.imaginea.store domain
routes = [
  { pattern = "pay.imaginea.store/*", zone_name = "imaginea.store" }
]

# Environment variables (will be set in Cloudflare dashboard)
[vars]
DODO_PAYMENTS_API_KEY = "h9mSEeGAVZw8FwWZ.WaEhI__Bceb1lRBLM-EtLmao8X8hfDcOR5URDLaHBQPh1qRr"
DODO_PAYMENTS_WEBHOOK_KEY = "whsec_JukXOg68DCPIJ8MjLcYfZLwlmZf4W+mV"
DODO_PAYMENTS_RETURN_URL = "https://pay.imaginea.store/payment-return"
DODO_PAYMENTS_ENVIRONMENT = "test_mode"

# If using KV for persistence (recommended)
[[kv_namespaces]]
binding = "PAYMENTS_STORE"
id = "your_kv_namespace_id"
preview_id = "your_kv_namespace_id"